#!/usr/bin/env bash
# This script displays all processes with STARTED time and CMD as headers

ps -eo user,lstart,cmd --sort=start_time | awk 'NR==1 {print "USER STARTED CMD"} NR>1 {print $1, $2, $3, $4, $5, $6, substr($0, index($0,$7))}'



